import Rachada1 from "../assets/images/Rachada1.jpg";
import Rachada2 from "../assets/images/Rachada2.jpg";
import Rachada3 from "../assets/images/Rachada3.jpg";
import Rachada4 from "../assets/images/Rachada4.jpg";
import Phaya from "../assets/images/Phaya.jpg";
import Bangkapi from "../assets/images/Bangkapi.jpg";
import Chatuchack1 from "../assets/images/Chatuchack1.jpg";
import Chatuchack2 from "../assets/images/Chatuchack2.jpg";
import RangRak from "../assets/images/RangRak.jpg";
import Watana1 from "../assets/images/Watana1.jpg";
import Watana2 from "../assets/images/Watana2.jpg";
import DinDaeng1 from "../assets/images/DinDaeng1.jpg";
import DinDaeng2 from "../assets/images/DinDaeng2.jpg";
export { Rachada1,Rachada2,Rachada3,Rachada4,Phaya,Bangkapi,Chatuchack1,Chatuchack2,RangRak,Watana1,Watana2,DinDaeng1,DinDaeng2 }
